syntax = "proto3";

package order_mgr;
// 相对路径;包名
option go_package = "./order_mgr_pb";

message BanPayPreOrderReq {
    string transaction_id = 1;
    string out_order_no = 2;
    string merchant_id = 3;
    int64 merchant_uid = 4;
    string merchant_name = 5;
    string user_id = 6;
    int64 uid = 7;
    int64 amount = 8;
}

message BanPayPreOrderRsp {
    string transaction_id = 1;
    int32 is_already_success = 2;
    OrderInfo order_info = 3;
}

message OrderInfo {
    string transaction_id = 1;
    string out_order_no = 2;
    string merchant_id = 3;
    int64 merchant_uid = 4;
    string merchant_name = 5;
    string user_id = 6;
    int64 uid = 7;
    int64 amount = 8;
    string pay_time = 9;
    int32 trade_state = 10;
    string order_success_token = 11;
}

message BanPaySuccessOrderReq {
    string transaction_id = 1;
    string out_order_no = 2;
    string merchant_id = 3;
    int64 merchant_uid = 4;
    string user_id = 5;
    int64 uid = 6;
    int64 amount = 7;
    string pay_time = 8;
    string deduct_token = 9;  // 扣款签名
}

message BanPaySuccessOrderRsp {
    OrderInfo order_info = 1;
}

message CloseOrderReq {
    string transaction_id = 1;
}

message CloseOrderRsp {
    string transaction_id = 1;
    int32 is_already_success = 2;
    OrderInfo order_info = 3;
}

message QueryOrderReq {
    string transaction_id = 1;
}

message QueryOrderRsp {
    OrderInfo order_info = 1;
}

service OrderMgr {    
    rpc BanPayPreOrder(BanPayPreOrderReq) returns (BanPayPreOrderRsp);
    rpc BanPaySuccessOrder(BanPaySuccessOrderReq) returns (BanPaySuccessOrderRsp);
    rpc CloseOrder(CloseOrderReq) returns (CloseOrderRsp);
    rpc QueryOrder(QueryOrderReq) returns (QueryOrderRsp);
}
