// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order_mgr.proto

package server

import (
	"context"

	"github.com/starslipay/order_mgr/internal/logic"
	"github.com/starslipay/order_mgr/internal/svc"
	"github.com/starslipay/order_mgr/order_mgr_pb"
)

type OrderMgrServer struct {
	svcCtx *svc.ServiceContext
	order_mgr_pb.UnimplementedOrderMgrServer
}

func NewOrderMgrServer(svcCtx *svc.ServiceContext) *OrderMgrServer {
	return &OrderMgrServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderMgrServer) BanPayPreOrder(ctx context.Context, in *order_mgr_pb.BanPayPreOrderReq) (*order_mgr_pb.BanPayPreOrderRsp, error) {
	l := logic.NewBanPayPreOrderLogic(ctx, s.svcCtx)
	return l.BanPayPreOrder(in)
}

func (s *OrderMgrServer) BanPaySuccessOrder(ctx context.Context, in *order_mgr_pb.BanPaySuccessOrderReq) (*order_mgr_pb.BanPaySuccessOrderRsp, error) {
	l := logic.NewBanPaySuccessOrderLogic(ctx, s.svcCtx)
	return l.BanPaySuccessOrder(in)
}

func (s *OrderMgrServer) CloseOrder(ctx context.Context, in *order_mgr_pb.CloseOrderReq) (*order_mgr_pb.CloseOrderRsp, error) {
	l := logic.NewCloseOrderLogic(ctx, s.svcCtx)
	return l.CloseOrder(in)
}

func (s *OrderMgrServer) QueryOrder(ctx context.Context, in *order_mgr_pb.QueryOrderReq) (*order_mgr_pb.QueryOrderRsp, error) {
	l := logic.NewQueryOrderLogic(ctx, s.svcCtx)
	return l.QueryOrder(in)
}
