// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tOrderFieldNames          = builder.RawFieldNames(&TOrder{})
	tOrderRows                = strings.Join(tOrderFieldNames, ",")
	tOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(tOrderFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(tOrderFieldNames, "`transaction_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tOrderModel interface {
		Insert(ctx context.Context, data *TOrder) (sql.Result, error)
		FindOne(ctx context.Context, transactionId string) (*TOrder, error)
		Update(ctx context.Context, data *TOrder) error
		Delete(ctx context.Context, transactionId string) error
	}

	defaultTOrderModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TOrder struct {
		TransactionId string    `db:"transaction_id"` // 交易ID
		Spid          string    `db:"spid"`           // 商户ID
		UserId        string    `db:"user_id"`        // 用户ID
		Uid           int64     `db:"uid"`            // 用户uid
		Amount        int64     `db:"amount"`         // 金额
		CurType       int64     `db:"cur_type"`       // 货币类型
		TradeState    int64     `db:"trade_state"`    // 交易状态
		PayType       int64     `db:"pay_type"`       // 支付类型
		PayTime       time.Time `db:"pay_time"`       // 支付时间
		CreateTime    time.Time `db:"create_time"`    // 创建时间
		UpdateTime    time.Time `db:"update_time"`    // 更新时间
	}
)

func newTOrderModel(conn sqlx.SqlConn) *defaultTOrderModel {
	return &defaultTOrderModel{
		conn:  conn,
		table: "`t_order`",
	}
}

func (m *defaultTOrderModel) Delete(ctx context.Context, transactionId string) error {
	query := fmt.Sprintf("delete from %s where `transaction_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, transactionId)
	return err
}

func (m *defaultTOrderModel) FindOne(ctx context.Context, transactionId string) (*TOrder, error) {
	query := fmt.Sprintf("select %s from %s where `transaction_id` = ? limit 1", tOrderRows, m.table)
	var resp TOrder
	err := m.conn.QueryRowCtx(ctx, &resp, query, transactionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTOrderModel) Insert(ctx context.Context, data *TOrder) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tOrderRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TransactionId, data.Spid, data.UserId, data.Uid, data.Amount, data.CurType, data.TradeState, data.PayType, data.PayTime)
	return ret, err
}

func (m *defaultTOrderModel) Update(ctx context.Context, data *TOrder) error {
	query := fmt.Sprintf("update %s set %s where `transaction_id` = ?", m.table, tOrderRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Spid, data.UserId, data.Uid, data.Amount, data.CurType, data.TradeState, data.PayType, data.PayTime, data.TransactionId)
	return err
}

func (m *defaultTOrderModel) tableName() string {
	return m.table
}
