// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order_mgr.proto

package ordermgr

import (
	"context"

	"github.com/starslipay/order_mgr/order_mgr_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BanPayPreOrderReq     = order_mgr_pb.BanPayPreOrderReq
	BanPayPreOrderRsp     = order_mgr_pb.BanPayPreOrderRsp
	BanPaySuccessOrderReq = order_mgr_pb.BanPaySuccessOrderReq
	BanPaySuccessOrderRsp = order_mgr_pb.BanPaySuccessOrderRsp
	CloseOrderReq         = order_mgr_pb.CloseOrderReq
	CloseOrderRsp         = order_mgr_pb.CloseOrderRsp
	OrderInfo             = order_mgr_pb.OrderInfo
	QueryOrderReq         = order_mgr_pb.QueryOrderReq
	QueryOrderRsp         = order_mgr_pb.QueryOrderRsp

	OrderMgr interface {
		BanPayPreOrder(ctx context.Context, in *BanPayPreOrderReq, opts ...grpc.CallOption) (*BanPayPreOrderRsp, error)
		BanPaySuccessOrder(ctx context.Context, in *BanPaySuccessOrderReq, opts ...grpc.CallOption) (*BanPaySuccessOrderRsp, error)
		CloseOrder(ctx context.Context, in *CloseOrderReq, opts ...grpc.CallOption) (*CloseOrderRsp, error)
		QueryOrder(ctx context.Context, in *QueryOrderReq, opts ...grpc.CallOption) (*QueryOrderRsp, error)
	}

	defaultOrderMgr struct {
		cli zrpc.Client
	}
)

func NewOrderMgr(cli zrpc.Client) OrderMgr {
	return &defaultOrderMgr{
		cli: cli,
	}
}

func (m *defaultOrderMgr) BanPayPreOrder(ctx context.Context, in *BanPayPreOrderReq, opts ...grpc.CallOption) (*BanPayPreOrderRsp, error) {
	client := order_mgr_pb.NewOrderMgrClient(m.cli.Conn())
	return client.BanPayPreOrder(ctx, in, opts...)
}

func (m *defaultOrderMgr) BanPaySuccessOrder(ctx context.Context, in *BanPaySuccessOrderReq, opts ...grpc.CallOption) (*BanPaySuccessOrderRsp, error) {
	client := order_mgr_pb.NewOrderMgrClient(m.cli.Conn())
	return client.BanPaySuccessOrder(ctx, in, opts...)
}

func (m *defaultOrderMgr) CloseOrder(ctx context.Context, in *CloseOrderReq, opts ...grpc.CallOption) (*CloseOrderRsp, error) {
	client := order_mgr_pb.NewOrderMgrClient(m.cli.Conn())
	return client.CloseOrder(ctx, in, opts...)
}

func (m *defaultOrderMgr) QueryOrder(ctx context.Context, in *QueryOrderReq, opts ...grpc.CallOption) (*QueryOrderRsp, error) {
	client := order_mgr_pb.NewOrderMgrClient(m.cli.Conn())
	return client.QueryOrder(ctx, in, opts...)
}
