// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: order_mgr.proto

package order_mgr_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BanPayPreOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Spid          string                 `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Uid           int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPayPreOrderReq) Reset() {
	*x = BanPayPreOrderReq{}
	mi := &file_order_mgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPayPreOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPayPreOrderReq) ProtoMessage() {}

func (x *BanPayPreOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_mgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPayPreOrderReq.ProtoReflect.Descriptor instead.
func (*BanPayPreOrderReq) Descriptor() ([]byte, []int) {
	return file_order_mgr_proto_rawDescGZIP(), []int{0}
}

func (x *BanPayPreOrderReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BanPayPreOrderReq) GetSpid() string {
	if x != nil {
		return x.Spid
	}
	return ""
}

func (x *BanPayPreOrderReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BanPayPreOrderReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BanPayPreOrderReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BanPayPreOrderRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderInfo     *OrderInfo             `protobuf:"bytes,3,opt,name=order_info,json=orderInfo,proto3" json:"order_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPayPreOrderRsp) Reset() {
	*x = BanPayPreOrderRsp{}
	mi := &file_order_mgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPayPreOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPayPreOrderRsp) ProtoMessage() {}

func (x *BanPayPreOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_mgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPayPreOrderRsp.ProtoReflect.Descriptor instead.
func (*BanPayPreOrderRsp) Descriptor() ([]byte, []int) {
	return file_order_mgr_proto_rawDescGZIP(), []int{1}
}

func (x *BanPayPreOrderRsp) GetOrderInfo() *OrderInfo {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

type OrderInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionId     string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Spid              string                 `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	UserId            string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Uid               int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Amount            int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PayTime           string                 `protobuf:"bytes,6,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	TradeState        int32                  `protobuf:"varint,7,opt,name=trade_state,json=tradeState,proto3" json:"trade_state,omitempty"`
	OrderSuccessToken string                 `protobuf:"bytes,8,opt,name=order_success_token,json=orderSuccessToken,proto3" json:"order_success_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_order_mgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_mgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_order_mgr_proto_rawDescGZIP(), []int{2}
}

func (x *OrderInfo) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *OrderInfo) GetSpid() string {
	if x != nil {
		return x.Spid
	}
	return ""
}

func (x *OrderInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *OrderInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderInfo) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *OrderInfo) GetTradeState() int32 {
	if x != nil {
		return x.TradeState
	}
	return 0
}

func (x *OrderInfo) GetOrderSuccessToken() string {
	if x != nil {
		return x.OrderSuccessToken
	}
	return ""
}

type BanPaySuccessOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Spid          string                 `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Uid           int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PayTime       string                 `protobuf:"bytes,6,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	DeductToken   string                 `protobuf:"bytes,7,opt,name=deduct_token,json=deductToken,proto3" json:"deduct_token,omitempty"` // 扣款签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPaySuccessOrderReq) Reset() {
	*x = BanPaySuccessOrderReq{}
	mi := &file_order_mgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPaySuccessOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPaySuccessOrderReq) ProtoMessage() {}

func (x *BanPaySuccessOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_mgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPaySuccessOrderReq.ProtoReflect.Descriptor instead.
func (*BanPaySuccessOrderReq) Descriptor() ([]byte, []int) {
	return file_order_mgr_proto_rawDescGZIP(), []int{3}
}

func (x *BanPaySuccessOrderReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BanPaySuccessOrderReq) GetSpid() string {
	if x != nil {
		return x.Spid
	}
	return ""
}

func (x *BanPaySuccessOrderReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BanPaySuccessOrderReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BanPaySuccessOrderReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BanPaySuccessOrderReq) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *BanPaySuccessOrderReq) GetDeductToken() string {
	if x != nil {
		return x.DeductToken
	}
	return ""
}

type BanPaySuccessOrderRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderInfo     *OrderInfo             `protobuf:"bytes,3,opt,name=order_info,json=orderInfo,proto3" json:"order_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPaySuccessOrderRsp) Reset() {
	*x = BanPaySuccessOrderRsp{}
	mi := &file_order_mgr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPaySuccessOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPaySuccessOrderRsp) ProtoMessage() {}

func (x *BanPaySuccessOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_mgr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPaySuccessOrderRsp.ProtoReflect.Descriptor instead.
func (*BanPaySuccessOrderRsp) Descriptor() ([]byte, []int) {
	return file_order_mgr_proto_rawDescGZIP(), []int{4}
}

func (x *BanPaySuccessOrderRsp) GetOrderInfo() *OrderInfo {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

type CloseOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Spid          string                 `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Uid           int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseOrderReq) Reset() {
	*x = CloseOrderReq{}
	mi := &file_order_mgr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseOrderReq) ProtoMessage() {}

func (x *CloseOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_mgr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseOrderReq.ProtoReflect.Descriptor instead.
func (*CloseOrderReq) Descriptor() ([]byte, []int) {
	return file_order_mgr_proto_rawDescGZIP(), []int{5}
}

func (x *CloseOrderReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CloseOrderReq) GetSpid() string {
	if x != nil {
		return x.Spid
	}
	return ""
}

func (x *CloseOrderReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CloseOrderReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CloseOrderReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CloseOrderRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderInfo     *OrderInfo             `protobuf:"bytes,3,opt,name=order_info,json=orderInfo,proto3" json:"order_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseOrderRsp) Reset() {
	*x = CloseOrderRsp{}
	mi := &file_order_mgr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseOrderRsp) ProtoMessage() {}

func (x *CloseOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_mgr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseOrderRsp.ProtoReflect.Descriptor instead.
func (*CloseOrderRsp) Descriptor() ([]byte, []int) {
	return file_order_mgr_proto_rawDescGZIP(), []int{6}
}

func (x *CloseOrderRsp) GetOrderInfo() *OrderInfo {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

type QueryOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOrderReq) Reset() {
	*x = QueryOrderReq{}
	mi := &file_order_mgr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderReq) ProtoMessage() {}

func (x *QueryOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_mgr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderReq.ProtoReflect.Descriptor instead.
func (*QueryOrderReq) Descriptor() ([]byte, []int) {
	return file_order_mgr_proto_rawDescGZIP(), []int{7}
}

func (x *QueryOrderReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type QueryOrderRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderInfo     *OrderInfo             `protobuf:"bytes,2,opt,name=order_info,json=orderInfo,proto3" json:"order_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOrderRsp) Reset() {
	*x = QueryOrderRsp{}
	mi := &file_order_mgr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderRsp) ProtoMessage() {}

func (x *QueryOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_mgr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderRsp.ProtoReflect.Descriptor instead.
func (*QueryOrderRsp) Descriptor() ([]byte, []int) {
	return file_order_mgr_proto_rawDescGZIP(), []int{8}
}

func (x *QueryOrderRsp) GetOrderInfo() *OrderInfo {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

var File_order_mgr_proto protoreflect.FileDescriptor

const file_order_mgr_proto_rawDesc = "" +
	"\n" +
	"\x0forder_mgr.proto\x12\torder_mgr\"\x91\x01\n" +
	"\x11BanPayPreOrderReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04spid\x18\x02 \x01(\tR\x04spid\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\"H\n" +
	"\x11BanPayPreOrderRsp\x123\n" +
	"\n" +
	"order_info\x18\x03 \x01(\v2\x14.order_mgr.OrderInfoR\torderInfo\"\xf5\x01\n" +
	"\tOrderInfo\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04spid\x18\x02 \x01(\tR\x04spid\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x19\n" +
	"\bpay_time\x18\x06 \x01(\tR\apayTime\x12\x1f\n" +
	"\vtrade_state\x18\a \x01(\x05R\n" +
	"tradeState\x12.\n" +
	"\x13order_success_token\x18\b \x01(\tR\x11orderSuccessToken\"\xd3\x01\n" +
	"\x15BanPaySuccessOrderReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04spid\x18\x02 \x01(\tR\x04spid\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x19\n" +
	"\bpay_time\x18\x06 \x01(\tR\apayTime\x12!\n" +
	"\fdeduct_token\x18\a \x01(\tR\vdeductToken\"L\n" +
	"\x15BanPaySuccessOrderRsp\x123\n" +
	"\n" +
	"order_info\x18\x03 \x01(\v2\x14.order_mgr.OrderInfoR\torderInfo\"\x8d\x01\n" +
	"\rCloseOrderReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04spid\x18\x02 \x01(\tR\x04spid\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\"D\n" +
	"\rCloseOrderRsp\x123\n" +
	"\n" +
	"order_info\x18\x03 \x01(\v2\x14.order_mgr.OrderInfoR\torderInfo\"6\n" +
	"\rQueryOrderReq\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"D\n" +
	"\rQueryOrderRsp\x123\n" +
	"\n" +
	"order_info\x18\x02 \x01(\v2\x14.order_mgr.OrderInfoR\torderInfo2\xb6\x02\n" +
	"\bOrderMgr\x12L\n" +
	"\x0eBanPayPreOrder\x12\x1c.order_mgr.BanPayPreOrderReq\x1a\x1c.order_mgr.BanPayPreOrderRsp\x12X\n" +
	"\x12BanPaySuccessOrder\x12 .order_mgr.BanPaySuccessOrderReq\x1a .order_mgr.BanPaySuccessOrderRsp\x12@\n" +
	"\n" +
	"CloseOrder\x12\x18.order_mgr.CloseOrderReq\x1a\x18.order_mgr.CloseOrderRsp\x12@\n" +
	"\n" +
	"QueryOrder\x12\x18.order_mgr.QueryOrderReq\x1a\x18.order_mgr.QueryOrderRspB\x10Z\x0e./order_mgr_pbb\x06proto3"

var (
	file_order_mgr_proto_rawDescOnce sync.Once
	file_order_mgr_proto_rawDescData []byte
)

func file_order_mgr_proto_rawDescGZIP() []byte {
	file_order_mgr_proto_rawDescOnce.Do(func() {
		file_order_mgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_mgr_proto_rawDesc), len(file_order_mgr_proto_rawDesc)))
	})
	return file_order_mgr_proto_rawDescData
}

var file_order_mgr_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_order_mgr_proto_goTypes = []any{
	(*BanPayPreOrderReq)(nil),     // 0: order_mgr.BanPayPreOrderReq
	(*BanPayPreOrderRsp)(nil),     // 1: order_mgr.BanPayPreOrderRsp
	(*OrderInfo)(nil),             // 2: order_mgr.OrderInfo
	(*BanPaySuccessOrderReq)(nil), // 3: order_mgr.BanPaySuccessOrderReq
	(*BanPaySuccessOrderRsp)(nil), // 4: order_mgr.BanPaySuccessOrderRsp
	(*CloseOrderReq)(nil),         // 5: order_mgr.CloseOrderReq
	(*CloseOrderRsp)(nil),         // 6: order_mgr.CloseOrderRsp
	(*QueryOrderReq)(nil),         // 7: order_mgr.QueryOrderReq
	(*QueryOrderRsp)(nil),         // 8: order_mgr.QueryOrderRsp
}
var file_order_mgr_proto_depIdxs = []int32{
	2, // 0: order_mgr.BanPayPreOrderRsp.order_info:type_name -> order_mgr.OrderInfo
	2, // 1: order_mgr.BanPaySuccessOrderRsp.order_info:type_name -> order_mgr.OrderInfo
	2, // 2: order_mgr.CloseOrderRsp.order_info:type_name -> order_mgr.OrderInfo
	2, // 3: order_mgr.QueryOrderRsp.order_info:type_name -> order_mgr.OrderInfo
	0, // 4: order_mgr.OrderMgr.BanPayPreOrder:input_type -> order_mgr.BanPayPreOrderReq
	3, // 5: order_mgr.OrderMgr.BanPaySuccessOrder:input_type -> order_mgr.BanPaySuccessOrderReq
	5, // 6: order_mgr.OrderMgr.CloseOrder:input_type -> order_mgr.CloseOrderReq
	7, // 7: order_mgr.OrderMgr.QueryOrder:input_type -> order_mgr.QueryOrderReq
	1, // 8: order_mgr.OrderMgr.BanPayPreOrder:output_type -> order_mgr.BanPayPreOrderRsp
	4, // 9: order_mgr.OrderMgr.BanPaySuccessOrder:output_type -> order_mgr.BanPaySuccessOrderRsp
	6, // 10: order_mgr.OrderMgr.CloseOrder:output_type -> order_mgr.CloseOrderRsp
	8, // 11: order_mgr.OrderMgr.QueryOrder:output_type -> order_mgr.QueryOrderRsp
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_order_mgr_proto_init() }
func file_order_mgr_proto_init() {
	if File_order_mgr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_mgr_proto_rawDesc), len(file_order_mgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_mgr_proto_goTypes,
		DependencyIndexes: file_order_mgr_proto_depIdxs,
		MessageInfos:      file_order_mgr_proto_msgTypes,
	}.Build()
	File_order_mgr_proto = out.File
	file_order_mgr_proto_goTypes = nil
	file_order_mgr_proto_depIdxs = nil
}
