// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: order_mgr.proto

package order_mgr_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderMgr_BanPayPreOrder_FullMethodName     = "/order_mgr.OrderMgr/BanPayPreOrder"
	OrderMgr_BanPaySuccessOrder_FullMethodName = "/order_mgr.OrderMgr/BanPaySuccessOrder"
	OrderMgr_CloseOrder_FullMethodName         = "/order_mgr.OrderMgr/CloseOrder"
	OrderMgr_QueryOrder_FullMethodName         = "/order_mgr.OrderMgr/QueryOrder"
)

// OrderMgrClient is the client API for OrderMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderMgrClient interface {
	BanPayPreOrder(ctx context.Context, in *BanPayPreOrderReq, opts ...grpc.CallOption) (*BanPayPreOrderRsp, error)
	BanPaySuccessOrder(ctx context.Context, in *BanPaySuccessOrderReq, opts ...grpc.CallOption) (*BanPaySuccessOrderRsp, error)
	CloseOrder(ctx context.Context, in *CloseOrderReq, opts ...grpc.CallOption) (*CloseOrderRsp, error)
	QueryOrder(ctx context.Context, in *QueryOrderReq, opts ...grpc.CallOption) (*QueryOrderRsp, error)
}

type orderMgrClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderMgrClient(cc grpc.ClientConnInterface) OrderMgrClient {
	return &orderMgrClient{cc}
}

func (c *orderMgrClient) BanPayPreOrder(ctx context.Context, in *BanPayPreOrderReq, opts ...grpc.CallOption) (*BanPayPreOrderRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BanPayPreOrderRsp)
	err := c.cc.Invoke(ctx, OrderMgr_BanPayPreOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderMgrClient) BanPaySuccessOrder(ctx context.Context, in *BanPaySuccessOrderReq, opts ...grpc.CallOption) (*BanPaySuccessOrderRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BanPaySuccessOrderRsp)
	err := c.cc.Invoke(ctx, OrderMgr_BanPaySuccessOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderMgrClient) CloseOrder(ctx context.Context, in *CloseOrderReq, opts ...grpc.CallOption) (*CloseOrderRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseOrderRsp)
	err := c.cc.Invoke(ctx, OrderMgr_CloseOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderMgrClient) QueryOrder(ctx context.Context, in *QueryOrderReq, opts ...grpc.CallOption) (*QueryOrderRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryOrderRsp)
	err := c.cc.Invoke(ctx, OrderMgr_QueryOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderMgrServer is the server API for OrderMgr service.
// All implementations must embed UnimplementedOrderMgrServer
// for forward compatibility.
type OrderMgrServer interface {
	BanPayPreOrder(context.Context, *BanPayPreOrderReq) (*BanPayPreOrderRsp, error)
	BanPaySuccessOrder(context.Context, *BanPaySuccessOrderReq) (*BanPaySuccessOrderRsp, error)
	CloseOrder(context.Context, *CloseOrderReq) (*CloseOrderRsp, error)
	QueryOrder(context.Context, *QueryOrderReq) (*QueryOrderRsp, error)
	mustEmbedUnimplementedOrderMgrServer()
}

// UnimplementedOrderMgrServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderMgrServer struct{}

func (UnimplementedOrderMgrServer) BanPayPreOrder(context.Context, *BanPayPreOrderReq) (*BanPayPreOrderRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method BanPayPreOrder not implemented")
}
func (UnimplementedOrderMgrServer) BanPaySuccessOrder(context.Context, *BanPaySuccessOrderReq) (*BanPaySuccessOrderRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method BanPaySuccessOrder not implemented")
}
func (UnimplementedOrderMgrServer) CloseOrder(context.Context, *CloseOrderReq) (*CloseOrderRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseOrder not implemented")
}
func (UnimplementedOrderMgrServer) QueryOrder(context.Context, *QueryOrderReq) (*QueryOrderRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryOrder not implemented")
}
func (UnimplementedOrderMgrServer) mustEmbedUnimplementedOrderMgrServer() {}
func (UnimplementedOrderMgrServer) testEmbeddedByValue()                  {}

// UnsafeOrderMgrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderMgrServer will
// result in compilation errors.
type UnsafeOrderMgrServer interface {
	mustEmbedUnimplementedOrderMgrServer()
}

func RegisterOrderMgrServer(s grpc.ServiceRegistrar, srv OrderMgrServer) {
	// If the following call panics, it indicates UnimplementedOrderMgrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderMgr_ServiceDesc, srv)
}

func _OrderMgr_BanPayPreOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanPayPreOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderMgrServer).BanPayPreOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderMgr_BanPayPreOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderMgrServer).BanPayPreOrder(ctx, req.(*BanPayPreOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderMgr_BanPaySuccessOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanPaySuccessOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderMgrServer).BanPaySuccessOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderMgr_BanPaySuccessOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderMgrServer).BanPaySuccessOrder(ctx, req.(*BanPaySuccessOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderMgr_CloseOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderMgrServer).CloseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderMgr_CloseOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderMgrServer).CloseOrder(ctx, req.(*CloseOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderMgr_QueryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderMgrServer).QueryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderMgr_QueryOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderMgrServer).QueryOrder(ctx, req.(*QueryOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderMgr_ServiceDesc is the grpc.ServiceDesc for OrderMgr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderMgr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order_mgr.OrderMgr",
	HandlerType: (*OrderMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BanPayPreOrder",
			Handler:    _OrderMgr_BanPayPreOrder_Handler,
		},
		{
			MethodName: "BanPaySuccessOrder",
			Handler:    _OrderMgr_BanPaySuccessOrder_Handler,
		},
		{
			MethodName: "CloseOrder",
			Handler:    _OrderMgr_CloseOrder_Handler,
		},
		{
			MethodName: "QueryOrder",
			Handler:    _OrderMgr_QueryOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_mgr.proto",
}
